### ISSUE TITLE
Titles of recalls

### ISSUE THREAD

**Issue by quidampepin** [gc-proto/recalls-safety#2]
To keep titles short, one option would be to keep them simple: brand+product. 

This would make sense in some situations, but not as much in others. For example, "Epilepsy drug primidone" doesn't give enough information scent to know what the problem is. If there is another recall for the same drug in the future, both recalls would have the same title and be indistinguishable in a search result list. There needs to be some kind of a qualifier (the date or the issue, for example). 

I'm on "brand/product+issue" team, as long as it's kept short. 

Something like:
Primidone - presence of lead
Buckley's Original - defective seals
Skip Hop Tuo convertible high chair - defective handle

**Comment by lisafast** [comment]
Interesting - this came up in the Vehicles and Emissions workshop today, particularly because of the Honda Pilot example. With just Brand-Product, all 5 would be called Honda - Pilot.

Think about the value of the word "Recall" in the title too. 

@ANNBELAN - could you take a list of 20 or 30 titles from across the whole range of RSAMS stuff and try out this method on them? If you look at the undeclared allergens, many already look like this. 

Oh Green brand Cereal recalled due to undeclared milk = Oh Green brand Cereal recall - undeclared milk

**Comment by ANNBELAN** [comment]
@lisafast  Haven't checked all 20-30 yet but searching like that seems to work well from the RSAMS home page (top result) but if I go into see all recalls then parse down to foods and then again to allergens and do the search not only does the search take FOREVER but it just gives you completely random results (like glass mugs and other un-relevant rubbish).

When I search "Kismet brand Methe Powder (Fenugreek Powder) recall - undeclared wheat" from the all recalls page it get gibberish even when I **narrow my search results**, first by food, then by allergens, then by wheat I'm still not getting a relevant result on the first page (though at least the ones I'm seeing are from 2018)

I've also noticed that if you type the actual title "La Cocina Dyck brand Tamales recalled due to undeclared wheat" instead of "La Cocina Dyck brand Tamales recall - undeclared wheat" you get the correct result  first (from within the all recalls search) but search result that is 1,000-3,000 long.

**Comment by sdkibb** [comment]
Is this repo still active and do you want contributors?

**Comment by lisafast** [comment]
Hi @sdkibb - this repo is "on hold" while Health Canada works on some back end processes. We have run a second validation round of task performance testing with Canadians on their mobile phones. It showed significant improvements in task success rates on this prototype versus the baseline existing Recalls site. 

We also made some additional design improvements based on behaviour in the Validation round of testing. 

That said, what kind of contribution did you have in mind? Always interested...

**Comment by sdkibb** [comment]
Makes sense, thanks for the info! I'm knowledgeable on the app having managed it for a few years and released the API in the GoC open data store as well as created the mobile app. So I'm good on contributing deep technical or otherwise via open contribution of through GoC Free Agent program. Mostly I'm  just glad to see this getting traction on moving forward. I suggested a user centered approach 5 years ago but with the tri-departmental complexities and having me, within IT, being the one to lead the revamp discussion it was a tough sell.

**Comment by lisafast** [comment]
Super, thanks @sdkibb 
The link to the prototyped design is http://search-recherche.gc.ca/rGsPreview/s_r?st=s&s5bm3ts21rch=x&num=10&st1rt=0&langs=eng&cdn=rasf&&
We post the testing results publicly on this page - once they've been translated etc. https://canada-ca.github.io/pages/projectoverview.html
